version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /home.html
    destination: /var/www/html/
  - source: /about.html
    destination: /var/www/html/
  - source: /contact.html
    destination: /var/www/html/
  - source: /login.html
    destination: /var/www/html/ 
hooks:
  BeforeInstall:
    - location: dep.sh
      timeout: 300
      runas: root
